name: Docker Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env: 
        DOCKER_USER: ${{ DOCKER_USER }}
        DOCKER_ACCESS_TOKEN: ${{ DOCKER_ACCESS_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_ACCESS_TOKEN
    - name: Build node application
      run: |
        npm ci
        npm run build
    - name: Build and push Docker images
      run: |
        docker build . -t anoppe/pihole-to-influx-js
        
      
